// Originally generated by Lovable. Edited deliberately — read the note below
// before regenerating it, because regenerating drops the fallback and that
// takes the whole site down.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

/**
 * The project this app talks to, as build-time defaults.
 *
 * Vite inlines `import.meta.env.VITE_*` **at build time**, so when these are
 * unset in the build environment the published bundle literally contains
 * `createClient(undefined, undefined)`. That throws `supabaseUrl is required`
 * while the module graph is still evaluating, `main.tsx` never runs, React never
 * mounts, and every page of the app is dead.
 *
 * That is not hypothetical — it is what happened the moment this branch merged.
 * A `.env` file used to be committed to the repository, so production builds
 * picked these values up from the working tree by accident. Phase 0 removed it,
 * which was right (it also held a billable Maps key), but nothing was set in the
 * host to replace it, so the next production build shipped a bundle that could
 * not boot. Prerendering then hid the failure: instead of a blank page, visitors
 * got the crawler-facing prose sitting there looking like a broken website.
 *
 * Committing the values back fixes that permanently and costs nothing, because
 * **both are publishable**. The URL is public, and the key is the anon
 * publishable key: it carries no authority of its own, everything it can reach
 * is behind row-level security, and it is served inside the JavaScript bundle to
 * every visitor regardless of where it is configured. Holding it in an
 * environment variable never made it secret — it only made the build fragile.
 *
 * Environment variables still win wherever they are set, so a preview or a fork
 * can point at a different project without touching this file.
 *
 * The service-role key is a different thing entirely. It bypasses RLS, it is not
 * here, it is not in the repository, and it must never be — Supabase injects it
 * into edge functions at runtime.
 */
const DEFAULT_SUPABASE_URL = 'https://skwzaxqhgrysbsuqkuyp.supabase.co';
const DEFAULT_SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_x_z5a2c_-tRAiHsj2W9dJg_qBz1IYPW';

/**
 * Exported because two other places need the same two values and were reading
 * `import.meta.env` for themselves — which meant they silently got `undefined`
 * in exactly the build that broke. `AIChatbot` posted to
 * `undefined/functions/v1/ai-chat`, and `useAuthProviders` took its
 * `if (!url || !key) return NONE` branch, which hides the Google and Apple
 * sign-in buttons. Neither threw; both just quietly stopped working.
 *
 * One resolution point, so a call site cannot disagree with the client.
 */
export const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || DEFAULT_SUPABASE_URL;
export const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || DEFAULT_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    /**
     * Passkeys (WebAuthn) are behind an explicit opt-in in supabase-js: without
     * this flag `auth.registerPasskey()`, `auth.signInWithPasskey()` and the
     * `auth.passkey.*` namespace throw synchronously at call time rather than
     * returning an error. The API is marked experimental upstream and may
     * change in a minor release — see src/lib/passkeys.ts, which is where the
     * shapes this app depends on are isolated.
     *
     * Turning the flag on costs nothing when the *project* has passkeys
     * disabled: the buttons are gated on the server's own `passkeys_enabled`
     * (see useAuthProviders), so nothing renders until the dashboard says so.
     */
    experimental: { passkey: true },
  }
});
